### ISSUE TITLE
FR: show form contents

### ISSUE THREAD

**Issue by edalzell** [silentzco/statamic-akismet#1]
When you click on submission in queue, pop up a modal to show the content.

**Comment by twd3** [comment]
Okay, I didn't know you couldn't view spam submission content right now. This is kind of a big one because I have not been able to confirm this addon is working by actually viewing a submission marked as spam. I logged in to Akismet hoping there was a way to see in there but nope. So, is this a million-dollar lead or spam? Who knows.

**Comment by edalzell** [comment]
In 2.2
